import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Search } from 'lucide-react';
import Layout from '@/components/layout/Layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { posts } from '@/data/blog';
const categories = ['All Posts', 'Web Design', 'UI/UX', 'E-Commerce', 'Business', 'Development'];
export default function Blog() {
 const [category, setCategory] = useState('All Posts'); const [search, setSearch] = useState('');
 const filtered = posts.filter(post => (category === 'All Posts' || post.category === category) && `${post.title} ${post.excerpt}`.toLowerCase().includes(search.toLowerCase()));
 return <Layout><section className="pt-36 pb-16"><div className="container mx-auto px-6"><span className="text-primary text-xs uppercase tracking-widest">The ByteVeo Journal</span><div className="grid md:grid-cols-2 gap-8 items-end mt-5"><h1 className="font-display text-6xl md:text-7xl font-bold leading-tight">Ideas.<br /><span className="text-gradient">Insights.</span></h1><p className="text-lg text-muted-foreground leading-relaxed max-w-md">Perspectives on design, development and the decisions that shape better digital businesses.</p></div></div></section><section className="pb-24"><div className="container mx-auto px-6"><div className="flex flex-col xl:flex-row justify-between gap-6 border-y border-border py-5 mb-10"><div className="flex flex-wrap gap-1">{categories.map(c => <Button key={c} variant={category === c ? 'default' : 'ghost'} size="sm" onClick={() => setCategory(c)} aria-pressed={category === c}>{c}</Button>)}</div><div className="relative max-w-xs w-full"><Search className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" /><Input aria-label="Search articles" placeholder="Search articles" value={search} onChange={e => setSearch(e.target.value)} className="pl-9" /></div></div><div className="blog-grid">{filtered.map((post, index) => <article key={post.slug} className="blog-card group bg-card border border-border rounded-lg overflow-hidden"><Link to={`/blog/${post.slug}`} className="block overflow-hidden"><img src={post.image} alt={post.title} width={1536} height={1024} loading="lazy" className={`w-full object-cover transition-transform duration-700 group-hover:scale-105 ${index % 3 === 1 ? 'aspect-[4/3]' : 'aspect-[3/2]'}`} /></Link><div className="p-5"><div className="flex justify-between text-xs text-muted-foreground"><span className="text-primary">{post.category}</span><span>{post.minutes} min read</span></div><h2 className="font-display text-xl font-semibold leading-snug mt-4"><Link to={`/blog/${post.slug}`} className="hover:text-primary">{post.title}</Link></h2><p className="text-muted-foreground text-sm leading-relaxed mt-3">{post.excerpt}</p><Button asChild variant="link" className="text-primary px-0 mt-4"><Link to={`/blog/${post.slug}`}>Read Article <ArrowUpRight /></Link></Button></div></article>)}</div>{filtered.length === 0 && <p className="text-muted-foreground text-center py-20">No articles found.</p>}</div></section></Layout>;
}
