import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowUpRight, Plus } from 'lucide-react';
import Layout from '@/components/layout/Layout';
import { Button } from '@/components/ui/button';
import { services } from '@/data/services';
import { visuals } from '@/data/projects';
export default function Services() { return <Layout><section className="pt-36 pb-16 border-b border-border"><div className="container mx-auto px-6"><span className="text-primary text-xs uppercase tracking-widest">Design & Technology</span><div className="grid lg:grid-cols-[1.3fr_1fr] gap-8 items-end mt-4"><h1 className="font-display text-5xl md:text-6xl font-bold leading-tight">Digital services.<br /><span className="text-gradient">Real possibilities.</span></h1><div><p className="text-muted-foreground text-lg leading-relaxed max-w-md">From your first idea to the next chapter, we bring design and engineering together to build what your business needs.</p><Button asChild className="mt-6 bg-gradient-gold text-primary-foreground"><Link to="/contact">Discuss Your Project <ArrowUpRight /></Link></Button></div></div><div className="flex flex-wrap gap-x-6 gap-y-3 mt-12">{services.map(s => <Link to={`#${s.id}`} key={s.id} className="text-sm text-muted-foreground hover:text-primary">{s.title} <span className="text-primary">↗</span></Link>)}</div></div></section>
 {services.map((service, index) => <section id={service.id} key={service.id} className="service-section scroll-mt-24 py-16 md:py-24 border-b border-border"><div className="container mx-auto px-6 grid md:grid-cols-2 gap-10 lg:gap-20 items-center"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className={index % 2 ? 'md:order-2' : ''}><img src={visuals[service.visual]} width={1536} height={1024} loading="lazy" alt={`${service.title} illustrative design concept`} className="w-full aspect-[3/2] object-cover rounded-lg" /><p className="text-xs text-muted-foreground mt-3">Illustrative design concept</p></motion.div><div><div className="flex items-center gap-3 text-primary"><span className="text-xs">0{index + 1}</span><service.icon className="w-5 h-5" /></div><h2 className="font-display text-3xl md:text-4xl font-semibold mt-4 leading-tight">{service.title}</h2><p className="text-muted-foreground leading-relaxed mt-5">{service.description}</p><div className="mt-7">{service.includes.map((item, i) => <details key={item} className="service-detail group border-b border-border"><summary className="flex items-center justify-between gap-3 cursor-pointer py-3 list-none text-sm"><span className="flex gap-4"><span className="text-muted-foreground text-xs pt-0.5">0{i + 1}</span>{item}</span><Plus className="w-4 h-4 text-muted-foreground group-open:rotate-45 transition-transform shrink-0" /></summary><p className="text-sm text-muted-foreground leading-relaxed pb-4 pl-8">We tailor {item.toLowerCase()} to your project, with a clear scope agreed before development begins.</p></details>)}</div><p className="text-sm text-muted-foreground mt-5">{service.forWho}</p><Button asChild variant="link" className="px-0 mt-3 text-primary"><Link to={`/contact?service=${encodeURIComponent(service.title)}`}>Contact for Pricing <ArrowUpRight /></Link></Button></div></div></section>)}
 <section className="py-24 bg-card/30"><div className="container mx-auto px-6 text-center"><h2 className="font-display text-4xl md:text-5xl font-semibold">What are we building next?</h2><p className="text-muted-foreground mt-5">Bring your idea. We will bring the right team.</p><Button asChild size="lg" className="mt-8 bg-gradient-gold text-primary-foreground"><Link to="/contact">Request a Quote <ArrowUpRight /></Link></Button></div></section></Layout>; }
